$( document ).ready(function() {
    getDataForDatatables();
});

function assignFilters() {
    $("$input[type=checkbox]").change(filter(this));
}
function filter(radio) {
    var r = radio.value;
	console.log(r.value);
    if (r == "all" && r.checked == "checked") {
        $("tr.dataRow").css("visibility", "visible");
    }
    else if (r == "all" && r.checked == "checked") {
		if (r.checked == "checked") {
        	$("tr.dataRow").css("visibility", "visible");
		}
		else {
			$("tr.dataRow").css("visibility", "hidden");
		}
    }
    else {

    }
}

function getDataForDatatables(){
    var jsonData = {  
        "data"     :     [
            {"name":"Bash","class":"Ironclad","type":"Attack","rarity":"Basic","cost":"2","desc":"Deal 8 (10) damage. Apply 2 (3) Vulnerable.","udesc":""},
            {"name":"Defend","class":"Ironclad","type":"Skill","rarity":"Basic","cost":"1","desc":"Gain 5 (8) Block.","udesc":""},
            {"name":"Strike","class":"Ironclad","type":"Attack","rarity":"Basic","cost":"1","desc":"Deal 6 (9) damage.","udesc":""},
            {"name":"Anger","class":"Ironclad","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 6 (8) damage. Add a copy of this card into your discard pile.","udesc":""},
            {"name":"Armaments","class":"Ironclad","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 5 Block. Upgrade a card in your hand for the rest of combat.","udesc":"Gain 5 Block. Upgrade all cards in your hand for the rest of combat."},
            {"name":"Body Slam","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1 (0)","desc":"Deal damage equal to your Block.","udesc":""},
            {"name":"Clash","class":"Ironclad","type":"Attack","rarity":"Common","cost":"0","desc":"Can only be played if every card in your hand is an Attack. Deal 14 (18) damage.","udesc":""},
            {"name":"Cleave","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 8 (11) damage to ALL enemies.","udesc":""},
            {"name":"Clothesline","class":"Ironclad","type":"Attack","rarity":"Common","cost":"2","desc":"Deal 12 (14) damage. Apply 2 (3) Weak.","udesc":""},
            {"name":"Flex","class":"Ironclad","type":"Skill","rarity":"Common","cost":"0","desc":"Gain 2 (4) Strength. At the end of this turn, lose 2 (4) Strength.","udesc":""},
            {"name":"Havoc","class":"Ironclad","type":"Skill","rarity":"Common","cost":"1 (0)","desc":"Play the top card of your draw pile and Exhaust it.","udesc":""},
            {"name":"Headbutt","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 9 (12) damage. Put a card from your discard pile on top of your draw pile.","udesc":""},
            {"name":"Heavy Blade","class":"Ironclad","type":"Attack","rarity":"Common","cost":"2","desc":"Deal 14 damage. Strength affects this card 3 (5) times.","udesc":""},
            {"name":"Iron Wave","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Gain 5 (7) Block. Deal 5 (7) damage.","udesc":""},
            {"name":"Perfected Strike","class":"Ironclad","type":"Attack","rarity":"Common","cost":"2","desc":"Deal 6 damage. Deals 2 (3) additional damage for ALL your cards containing \"Strike\".","udesc":""},
            {"name":"Pommel Strike","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 9 damage. Draw 1 card.","udesc":"Deal 10 damage. Draw 2 cards."},
            {"name":"Shrug It Off","class":"Ironclad","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 8 (11) Block. Draw 1 card.","udesc":""},
            {"name":"Sword Boomerang","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 3 damage to a random enemy 3 (4) times.","udesc":""},
            {"name":"Thunderclap","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 4 (7) damage and apply 1 Vulnerable to ALL enemies.","udesc":""},
            {"name":"True Grit","class":"Ironclad","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 7 Block. Exhaust 1 card at random.","udesc":"Gain 9 Block. Exhaust 1 card."},
            {"name":"Twin Strike","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 5 (7) damage twice.","udesc":""},
            {"name":"Warcry","class":"Ironclad","type":"Skill","rarity":"Common","cost":"0","desc":"Draw 1 card. Put a card from your hand onto the top of your draw pile. Exhaust.","udesc":"Draw 2 cards. Put a card from your hand onto the top of your draw pile. Exhaust."},
            {"name":"Wild Strike","class":"Ironclad","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 12 (17) damage. Shuffle a Wound into your draw pile.","udesc":""},
            {"name":"Battle Trance","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Draw 3 (4) cards. You cannot draw additional cards this turn.","udesc":""},
            {"name":"Blood for Blood","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"4 (3)","desc":"Costs 1 less [R] for each time you lose HP this combat. Deal 18 (22) damage.","udesc":""},
            {"name":"Bloodletting","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Lose 3 HP. Gain [R] [R].","udesc":"Lose 3 HP. Gain [R] [R] [R]."},
            {"name":"Burning Pact","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Exhaust 1 card. Draw 2 (3) cards.","udesc":""},
            {"name":"Carnage","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Ethereal. Deal 20 (28) damage.","udesc":""},
            {"name":"Combust","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the end of your turn, lose 1 HP and deal 5 (7) damage to ALL enemies.","udesc":""},
            {"name":"Dark Embrace","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"2 (1)","desc":"Whenever a card is Exhausted, draw 1 card.","udesc":""},
            {"name":"Disarm","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Enemy loses 2 (3) Strength. Exhaust.","udesc":""},
            {"name":"Dropkick","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 5 (8) damage. If the enemy has Vulnerable, gain [R] and draw 1 card.","udesc":""},
            {"name":"Dual Wield","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Choose an Attack or Power card. Add a copy of that card into your hand.","udesc":"Choose an Attack or Power card. Add 2 copies of that card into your hand."},
            {"name":"Entrench","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"2 (1)","desc":"Double your Block.","udesc":""},
            {"name":"Evolve","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you draw a Status card, draw 1 card.","udesc":"Whenever you draw a Status card, draw 2 cards."},
            {"name":"Feel No Pain","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever a card is Exhausted, gain 3 (4) Block.","udesc":""},
            {"name":"Fire Breathing","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you draw a Status or Curse card, deal 6 (10) damage to ALL enemies.","udesc":""},
            {"name":"Flame Barrier","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Gain 12 (16) Block. Whenever you are attacked this turn, deal 4 (6) damage back.","udesc":""},
            {"name":"Ghostly Armor","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Ethereal. Gain 10 (13) Block.","udesc":""},
            {"name":"Hemokinesis","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Lose 2 HP. Deal 15 (20) damage.","udesc":""},
            {"name":"Infernal Blade","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Add a random Attack into your hand. It costs 0 this turn. Exhaust.","udesc":""},
            {"name":"Inflame","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"Gain 2 (3) Strength.","udesc":""},
            {"name":"Intimidate","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Apply 1 (2) Weak to ALL enemies. Exhaust.","udesc":""},
            {"name":"Metallicize","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the end of your turn, gain 3 (4) Block.","udesc":""},
            {"name":"Power Through","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Add 2 Wounds into your hand. Gain 15 (20) Block.","udesc":""},
            {"name":"Pummel","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 2 damage 4 (5) times. Exhaust.","udesc":""},
            {"name":"Rage","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Whenever you play an Attack this turn, gain 3 (5) Block.","udesc":""},
            {"name":"Rampage","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 8 damage. Increase this card's damage by 5 (8) this combat.","udesc":""},
            {"name":"Reckless Charge","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Deal 7 (10) damage. Shuffle a Dazed into your draw pile.","udesc":""},
            {"name":"Rupture","class":"Ironclad","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you lose HP from a card, gain 1 (2) Strength.","udesc":""},
            {"name":"Searing Blow","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 12 (16) damage. Can be Upgraded any number of times.","udesc":""},
            {"name":"Second Wind","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Exhaust all non-Attack cards in your hand. Gain 5 (7) Block for each card Exhausted.","udesc":""},
            {"name":"Seeing Red","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Gain [R] [R]. Exhaust.","udesc":""},
            {"name":"Sentinel","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain 5 Block. If this card is Exhausted, gain [R] [R].","udesc":"Gain 8 Block. If this card is Exhausted, gain [R] [R] [R]."},
            {"name":"Sever Soul","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Exhaust all non-Attack cards in your hand. Deal 16 (22) damage.","udesc":""},
            {"name":"Shockwave","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Apply 3 (5) Weak and Vulnerable to ALL enemies. Exhaust.","udesc":""},
            {"name":"Spot Weakness","class":"Ironclad","type":"Skill","rarity":"Uncommon","cost":"1","desc":"If the enemy intends to attack, gain 3 (4) Strength.","udesc":""},
            {"name":"Uppercut","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 13 damage. Apply 1 (2) Weak. Apply 1 (2) Vulnerable.","udesc":""},
            {"name":"Whirlwind","class":"Ironclad","type":"Attack","rarity":"Uncommon","cost":"X","desc":"Deal 5 (8) damage to ALL enemies X times.","udesc":""},
            {"name":"Barricade","class":"Ironclad","type":"Power","rarity":"Rare","cost":"3 (2)","desc":"Block is not removed at the start of your turn.","udesc":""},
            {"name":"Berserk","class":"Ironclad","type":"Power","rarity":"Rare","cost":"0","desc":"Gain 2 (1) Vulnerable. At the start of your turn, gain [R].","udesc":""},
            {"name":"Bludgeon","class":"Ironclad","type":"Attack","rarity":"Rare","cost":"3","desc":"Deal 32 (42) damage.","udesc":""},
            {"name":"Brutality","class":"Ironclad","type":"Power","rarity":"Rare","cost":"0","desc":"At the start of your turn, lose 1 HP and draw 1 card.","udesc":"Innate. At the start of your turn, lose 1 HP and draw 1 card."},
            {"name":"Corruption","class":"Ironclad","type":"Power","rarity":"Rare","cost":"3 (2)","desc":"Skills cost 0. Whenever you play a Skill, Exhaust it.","udesc":""},
            {"name":"Demon Form","class":"Ironclad","type":"Power","rarity":"Rare","cost":"3","desc":"At the start of your turn, gain 2 (3) Strength.","udesc":""},
            {"name":"Double Tap","class":"Ironclad","type":"Skill","rarity":"Rare","cost":"1","desc":"This turn, your next Attack is played twice.","udesc":"This turn, your next 2 Attacks are played twice."},
            {"name":"Exhume","class":"Ironclad","type":"Skill","rarity":"Rare","cost":"1 (0)","desc":"Put a card from your exhaust pile into your hand. Exhaust.","udesc":""},
            {"name":"Feed","class":"Ironclad","type":"Attack","rarity":"Rare","cost":"1","desc":"Deal 10 (12) damage. If Fatal, raise your Max HP by 3 (4). Exhaust.","udesc":""},
            {"name":"Fiend Fire","class":"Ironclad","type":"Attack","rarity":"Rare","cost":"2","desc":"Exhaust your hand. Deal 7 (10) damage for each card Exhausted. Exhaust.","udesc":""},
            {"name":"Immolate","class":"Ironclad","type":"Attack","rarity":"Rare","cost":"2","desc":"Deal 21 (28) damage to ALL enemies. Add a Burn into your discard pile.","udesc":""},
            {"name":"Impervious","class":"Ironclad","type":"Skill","rarity":"Rare","cost":"2","desc":"Gain 30 (40) Block. Exhaust.","udesc":""},
            {"name":"Juggernaut","class":"Ironclad","type":"Power","rarity":"Rare","cost":"2","desc":"Whenever you gain Block, deal 5 (7) damage to a random enemy.","udesc":""},
            {"name":"Limit Break","class":"Ironclad","type":"Skill","rarity":"Rare","cost":"1","desc":"Double your Strength. Exhaust.","udesc":"Double your Strength."},
            {"name":"Offering","class":"Ironclad","type":"Skill","rarity":"Rare","cost":"0","desc":"Lose 6 HP. Gain [R] [R]. Draw 3 (5) cards. Exhaust.","udesc":""},
            {"name":"Reaper","class":"Ironclad","type":"Attack","rarity":"Rare","cost":"2","desc":"Deal 4 (5) damage to ALL enemies. Heal HP equal to unblocked damage. Exhaust.","udesc":""},
            {"name":"Defend","class":"Silent","type":"Skill","rarity":"Basic","cost":"1","desc":"Gain 5 (8) Block.","udesc":""},
            {"name":"Neutralize","class":"Silent","type":"Attack","rarity":"Basic","cost":"0","desc":"Deal 3 (4) damage. Apply 1 (2) Weak.","udesc":""},
            {"name":"Strike","class":"Silent","type":"Attack","rarity":"Basic","cost":"1","desc":"Deal 6 (9) damage.","udesc":""},
            {"name":"Survivor","class":"Silent","type":"Skill","rarity":"Basic","cost":"1","desc":"Gain 8 (11) Block. Discard 1 card.","udesc":""},
            {"name":"Acrobatics","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Draw 3 (4) cards. Discard 1 card.","udesc":""},
            {"name":"Backflip","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 5 (8) Block. Draw 2 cards.","udesc":""},
            {"name":"Bane","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (10) damage. If the enemy has Poison, deal 7 (10) damage again.","udesc":""},
            {"name":"Blade Dance","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Add 3 (4) Shivs into your hand.","udesc":""},
            {"name":"Cloak and Dagger","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 6 Block. Add 1 Shiv into your hand.","udesc":"Gain 6 Block. Add 2 Shivs into your hand."},
            {"name":"Dagger Spray","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 4 (6) damage to ALL enemies twice.","udesc":""},
            {"name":"Dagger Throw","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 9 (12) damage. Draw 1 card. Discard 1 card.","udesc":""},
            {"name":"Deadly Poison","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Apply 5 (7) Poison.","udesc":""},
            {"name":"Deflect","class":"Silent","type":"Skill","rarity":"Common","cost":"0","desc":"Gain 4 (7) Block.","udesc":""},
            {"name":"Dodge and Roll","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 4 (6) Block. Next turn, gain 4 (6) Block.","udesc":""},
            {"name":"Flying Knee","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 8 (11) damage. Next turn, gain [G].","udesc":""},
            {"name":"Outmaneuver","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"Next turn, gain [G] [G].","udesc":"Next turn, gain [G] [G] [G]."},
            {"name":"Piercing Wail","class":"Silent","type":"Skill","rarity":"Common","cost":"1","desc":"ALL enemies lose 6 (8) Strength this turn. Exhaust.","udesc":""},
            {"name":"Poisoned Stab","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 6 (8) damage. Apply 3 (4) Poison.","udesc":""},
            {"name":"Prepared","class":"Silent","type":"Skill","rarity":"Common","cost":"0","desc":"Draw 1 card. Discard 1 card.","udesc":"Draw 2 cards. Discard 2 cards."},
            {"name":"Quick Slash","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 8 (12) damage. Draw 1 card.","udesc":""},
            {"name":"Slice","class":"Silent","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 6 (9) damage.","udesc":""},
            {"name":"Sneaky Strike","class":"Silent","type":"Attack","rarity":"Common","cost":"2","desc":"Deal 12 (16) damage. If you have discarded a card this turn, gain [G] [G].","udesc":""},
            {"name":"Sucker Punch","class":"Silent","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (9) damage. Apply 1 (2) Weak.","udesc":""},
            {"name":"Accuracy","class":"Silent","type":"Power","rarity":"Uncommon","cost":"1","desc":"Shivs deal 4 (6) additional damage.","udesc":""},
            {"name":"All-Out Attack","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 10 (14) damage to ALL enemies. Discard 1 card at random.","udesc":""},
            {"name":"Backstab","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Innate. Deal 11 (15) damage. Exhaust.","udesc":""},
            {"name":"Blur","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain 5 (8) Block. Block is not removed at the start of your next turn.","udesc":""},
            {"name":"Bouncing Flask","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Apply 3 Poison to a random enemy 3 (4) times.","udesc":""},
            {"name":"Calculated Gamble","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Discard your hand, then draw that many cards. Exhaust.","udesc":"Discard your hand, then draw that many cards."},
            {"name":"Caltrops","class":"Silent","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you are attacked, deal 3 (5) damage back.","udesc":""},
            {"name":"Catalyst","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Double the enemy's Poison. Exhaust.","udesc":"Triple the enemy's Poison. Exhaust."},
            {"name":"Choke","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 12 damage. Whenever you play a card this turn, the enemy loses 3 (5) HP.","udesc":""},
            {"name":"Concentrate","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Discard 3 (2) cards. Gain [G] [G].","udesc":""},
            {"name":"Crippling Cloud","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Apply 4 (7) Poison and 2 Weak to ALL enemies. Exhaust.","udesc":""},
            {"name":"Dash","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Gain 10 (13) Block. Deal 10 (13) damage.","udesc":""},
            {"name":"Distraction","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Add a random Skill into your hand. It costs 0 this turn. Exhaust.","udesc":""},
            {"name":"Endless Agony","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Deal 4 (6) damage. Whenever you draw this card, add a copy of it into your hand. Exhaust.","udesc":""},
            {"name":"Escape Plan","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Draw 1 card. If you draw a Skill, gain 3 (5) Block.","udesc":""},
            {"name":"Eviscerate","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"3","desc":"Costs 1 less [G] for each card discarded this turn. Deal 7 (9) damage 3 times.","udesc":""},
            {"name":"Expertise","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Draw cards until you have 6 (7) in your hand.","udesc":""},
            {"name":"Finisher","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 6 (8) damage for each Attack played this turn.","udesc":""},
            {"name":"Flechettes","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 4 (6) damage for each Skill in your hand.","udesc":""},
            {"name":"Footwork","class":"Silent","type":"Power","rarity":"Uncommon","cost":"1","desc":"Gain 2 (3) Dexterity.","udesc":""},
            {"name":"Heel Hook","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 5 (8) damage. If the enemy has Weak, gain [G] and draw 1 card.","udesc":""},
            {"name":"Infinite Blades","class":"Silent","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the start of your turn, add a Shiv into your hand.","udesc":"Innate. At the start of your turn, add a Shiv into your hand."},
            {"name":"Leg Sweep","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Apply 2 (3) Weak. Gain 11 (14) Block.","udesc":""},
            {"name":"Masterful Stab","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Costs 1 additional [G] for each time you lose HP this combat. Deal 12 (16) damage.","udesc":""},
            {"name":"Noxious Fumes","class":"Silent","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the start of your turn, apply 2 (3) Poison to ALL enemies.","udesc":""},
            {"name":"Predator","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 15 (20) damage. Next turn, draw 2 additional cards.","udesc":""},
            {"name":"Reflex","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"-","desc":"Unplayable. If this card is discarded from your hand, draw 2 cards.","udesc":"Unplayable. If this card is discarded from your hand, draw 3 cards."},
            {"name":"Riddle with Holes","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 3 (4) damage 5 times.","udesc":""},
            {"name":"Setup","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Put a card from your hand on top of your draw pile. It costs 0 until played.","udesc":""},
            {"name":"Skewer","class":"Silent","type":"Attack","rarity":"Uncommon","cost":"X","desc":"Deal 7 (10) damage X times.","udesc":""},
            {"name":"Tactician","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"-","desc":"Unplayable. If this card is discarded from your hand, gain [G].","udesc":"Unplayable. If this card is discarded from your hand, gain [G] [G]."},
            {"name":"Terror","class":"Silent","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Apply 99 Vulnerable. Exhaust.","udesc":""},
            {"name":"Well-Laid Plans","class":"Silent","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the end of your turn, Retain up to 1 card.","udesc":"At the end of your turn, Retain up to 2 cards."},
            {"name":"A Thousand Cuts","class":"Silent","type":"Power","rarity":"Rare","cost":"2","desc":"Whenever you play a card, deal 1 (2) damage to ALL enemies.","udesc":""},
            {"name":"Adrenaline","class":"Silent","type":"Skill","rarity":"Rare","cost":"0","desc":"Gain [G]. Draw 2 cards. Exhaust.","udesc":"Gain [G] [G]. Draw 2 cards. Exhaust."},
            {"name":"After Image","class":"Silent","type":"Power","rarity":"Rare","cost":"1","desc":"Whenever you play a card, gain 1 Block.","udesc":"Innate. Whenever you play a card, gain 1 Block."},
            {"name":"Alchemize","class":"Silent","type":"Skill","rarity":"Rare","cost":"1 (0)","desc":"Obtain a random potion. Exhaust.","udesc":""},
            {"name":"Bullet Time","class":"Silent","type":"Skill","rarity":"Rare","cost":"3 (2)","desc":"You cannot draw additional cards this turn. Reduce the cost of all cards in your hand to 0 this turn.","udesc":""},
            {"name":"Burst","class":"Silent","type":"Skill","rarity":"Rare","cost":"1","desc":"This turn, your next Skill is played twice.","udesc":"This turn, your next 2 Skills are played twice."},
            {"name":"Corpse Explosion","class":"Silent","type":"Skill","rarity":"Rare","cost":"2","desc":"Apply 6 (9) Poison. When the enemy dies, deal damage equal to its Max HP to ALL enemies.","udesc":""},
            {"name":"Die Die Die","class":"Silent","type":"Attack","rarity":"Rare","cost":"1","desc":"Deal 13 (17) damage to ALL enemies. Exhaust.","udesc":""},
            {"name":"Doppelganger","class":"Silent","type":"Skill","rarity":"Rare","cost":"X","desc":"Next turn, draw X cards and gain X [G]. Exhaust.","udesc":"Next turn, draw X+1 cards and gain X+1 [G]. Exhaust."},
            {"name":"Envenom","class":"Silent","type":"Power","rarity":"Rare","cost":"2 (1)","desc":"Whenever an Attack deals unblocked damage, apply 1 Poison.","udesc":""},
            {"name":"Glass Knife","class":"Silent","type":"Attack","rarity":"Rare","cost":"1","desc":"Deal 8 (12) damage twice. Decrease the damage of this card by 2 this combat.","udesc":""},
            {"name":"Grand Finale","class":"Silent","type":"Attack","rarity":"Rare","cost":"0","desc":"Can only be played if there are no cards in your draw pile. Deal 50 (60) damage to ALL enemies.","udesc":""},
            {"name":"Malaise","class":"Silent","type":"Skill","rarity":"Rare","cost":"X","desc":"Enemy loses X Strength. Apply X Weak. Exhaust.","udesc":"Enemy loses X+1 Strength. Apply X+1 Weak. Exhaust."},
            {"name":"Nightmare","class":"Silent","type":"Skill","rarity":"Rare","cost":"3 (2)","desc":"Choose a card. Next turn, add 3 copies of that card into your hand. Exhaust.","udesc":""},
            {"name":"Phantasmal Killer","class":"Silent","type":"Skill","rarity":"Rare","cost":"1 (0)","desc":"Next turn, your Attacks deal double damage.","udesc":""},
            {"name":"Storm of Steel","class":"Silent","type":"Skill","rarity":"Rare","cost":"1","desc":"Discard your hand. Add 1 Shiv into your hand for each card discarded.","udesc":"Discard your hand. Add 1 Shiv+ into your hand for each card discarded."},
            {"name":"Tools of the Trade","class":"Silent","type":"Power","rarity":"Rare","cost":"1 (0)","desc":"At the start of your turn, draw 1 card and discard 1 card.","udesc":""},
            {"name":"Unload","class":"Silent","type":"Attack","rarity":"Rare","cost":"1","desc":"Deal 14 (18) damage. Discard all non-Attack cards in your hand.","udesc":""},
            {"name":"Wraith Form","class":"Silent","type":"Power","rarity":"Rare","cost":"3","desc":"Gain 2 (3) Intangible. At the end of your turn, lose 1 Dexterity.","udesc":""},
            {"name":"Defend","class":"Defect","type":"Skill","rarity":"Basic","cost":"1","desc":"Gain 5 (8) Block.","udesc":""},
            {"name":"Dualcast","class":"Defect","type":"Skill","rarity":"Basic","cost":"1 (0)","desc":"Evoke your next Orb twice.","udesc":""},
            {"name":"Strike","class":"Defect","type":"Attack","rarity":"Basic","cost":"1","desc":"Deal 6 (9) damage.","udesc":""},
            {"name":"Zap","class":"Defect","type":"Skill","rarity":"Basic","cost":"1 (0)","desc":"Channel 1 Lightning.","udesc":""},
            {"name":"Ball Lightning","class":"Defect","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (10) damage. Channel 1 Lightning.","udesc":""},
            {"name":"Barrage","class":"Defect","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 4 (6) damage for each Channeled Orb.","udesc":""},
            {"name":"Beam Cell","class":"Defect","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 3 (4) damage. Apply 1 (2) Vulnerable.","udesc":""},
            {"name":"Charge Battery","class":"Defect","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 7 (10) Block. Next turn, gain [B].","udesc":""},
            {"name":"Claw","class":"Defect","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 3 (5) damage. Increase the damage of ALL Claw cards by 2 this combat.","udesc":""},
            {"name":"Cold Snap","class":"Defect","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 6 (9) damage. Channel 1 Frost.","udesc":""},
            {"name":"Compile Driver","class":"Defect","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (10) damage. Draw 1 card for each unique Orb you have.","udesc":""},
            {"name":"Coolheaded","class":"Defect","type":"Skill","rarity":"Common","cost":"1","desc":"Channel 1 Frost. Draw 1 card.","udesc":"Channel 1 Frost. Draw 2 cards."},
            {"name":"Go for the Eyes","class":"Defect","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 3 (4) damage. If the enemy intends to attack, apply 1 (2) Weak.","udesc":""},
            {"name":"Hologram","class":"Defect","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 3 Block. Put a card from your discard pile into your hand. Exhaust.","udesc":"Gain 5 Block. Put a card from your discard pile into your hand."},
            {"name":"Leap","class":"Defect","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 9 (12) Block.","udesc":""},
            {"name":"Rebound","class":"Defect","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 9 (12) damage. Put the next card you play this turn on top of your draw pile.","udesc":""},
            {"name":"Recursion","class":"Defect","type":"Skill","rarity":"Common","cost":"1 (0)","desc":"Evoke your next Orb. Channel the Orb that was just Evoked.","udesc":""},
            {"name":"Stack","class":"Defect","type":"Skill","rarity":"Common","cost":"1","desc":"Gain Block equal to the number of cards in your discard pile.","udesc":"Gain Block equal to the number of cards in your discard pile +3."},
            {"name":"Steam Barrier","class":"Defect","type":"Skill","rarity":"Common","cost":"0","desc":"Gain 6 (8) Block. Decrease this card's Block by 1 this combat.","udesc":""},
            {"name":"Streamline","class":"Defect","type":"Attack","rarity":"Common","cost":"2","desc":"Deal 15 (20) damage. Reduce this card's cost by 1 this combat.","udesc":""},
            {"name":"Sweeping Beam","class":"Defect","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 6 (9) damage to ALL enemies. Draw 1 card.","udesc":""},
            {"name":"TURBO","class":"Defect","type":"Skill","rarity":"Common","cost":"0","desc":"Gain [B] [B]. Add a Void into your discard pile.","udesc":"Gain [B] [B] [B]. Add a Void into your discard pile."},
            {"name":"Aggregate","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain [B] for every 4 (3) cards in your draw pile.","udesc":""},
            {"name":"Auto-Shields","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"If you have no Block, gain 11 (15) Block.","udesc":""},
            {"name":"Blizzard","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal damage equal to 2 (3) times the number of Frost Channeled this combat to ALL enemies.","udesc":""},
            {"name":"Boot Sequence","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Innate. Gain 10 (13) Block. Exhaust.","udesc":""},
            {"name":"Bullseye","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 8 (11) damage. Apply 2 (3) Lock-On.","udesc":""},
            {"name":"Capacitor","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"Gain 2 (3) Orb slots.","udesc":""},
            {"name":"Chaos","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Channel 1 random Orb.","udesc":"Channel 2 random Orbs."},
            {"name":"Chill","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Channel 1 Frost for each enemy in combat. Exhaust.","udesc":"Innate. Channel 1 Frost for each enemy in combat. Exhaust."},
            {"name":"Consume","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Gain 2 (3) Focus. Lose 1 Orb slot.","udesc":""},
            {"name":"Darkness","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Channel 1 Dark.","udesc":"Channel 1 Dark. Trigger the passive ability of all Dark orbs."},
            {"name":"Defragment","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"Gain 1 (2) Focus.","udesc":""},
            {"name":"Doom and Gloom","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 10 (14) damage to ALL enemies. Channel 1 Dark.","udesc":""},
            {"name":"Double Energy","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Double your Energy. Exhaust.","udesc":""},
            {"name":"Equilibrium","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Gain 13 (16) Block. Retain your hand this turn.","udesc":""},
            {"name":"FTL","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Deal 5 (6) damage. If you have played less than 3 (4) cards this turn, draw 1 card.","udesc":""},
            {"name":"Force Field","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"4","desc":"Costs 1 less [B] for each Power card played this combat. Gain 12 (16) Block.","udesc":""},
            {"name":"Fusion","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"2 (1)","desc":"Channel 1 Plasma.","udesc":""},
            {"name":"Genetic Algorithm","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain 1 Block. Permanently increase this card's Block by 2 (3). Exhaust.","udesc":""},
            {"name":"Glacier","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Gain 7 (10) Block. Channel 2 Frost.","udesc":""},
            {"name":"Heatsinks","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you play a Power card, draw 1 card.","udesc":"Whenever you play a Power card, draw 2 cards."},
            {"name":"Hello World","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the start of your turn, add a random Common card into your hand.","udesc":"Innate. At the start of your turn, add a random Common card into your hand."},
            {"name":"Loop","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the start of your turn, trigger the passive ability of your next Orb.","udesc":"At the start of your turn, trigger the passive ability of your next Orb 2 times."},
            {"name":"Melter","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Remove all Block from the enemy. Deal 10 (14) damage.","udesc":""},
            {"name":"Overclock","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Draw 2 (3) cards. Add a Burn into your discard pile.","udesc":""},
            {"name":"Recycle","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Exhaust a card. Gain [B] equal to its cost.","udesc":""},
            {"name":"Reinforced Body","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"X","desc":"Gain 7 (9) Block X times.","udesc":""},
            {"name":"Reprogram","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Lose 1 (2) Focus. Gain 1 (2) Strength. Gain 1 (2) Dexterity.","udesc":""},
            {"name":"Rip and Tear","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 7 (9) damage to a random enemy twice.","udesc":""},
            {"name":"Scrape","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 7 (10) damage. Draw 4 (5) cards. Discard all cards drawn this way that do not cost 0.","udesc":""},
            {"name":"Self Repair","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the end of combat, heal 7 (10) HP.","udesc":""},
            {"name":"Skim","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Draw 3 (4) cards.","udesc":""},
            {"name":"Static Discharge","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you receive unblocked attack damage, Channel 1 (2) Lightning.","udesc":""},
            {"name":"Storm","class":"Defect","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you play a Power card, Channel 1 Lightning.","udesc":"Innate. Whenever you play a Power card, Channel 1 Lightning."},
            {"name":"Sunder","class":"Defect","type":"Attack","rarity":"Uncommon","cost":"3","desc":"Deal 24 (32) damage. If this kills an enemy, gain [B] [B] [B].","udesc":""},
            {"name":"Tempest","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"X","desc":"Channel X Lightning. Exhaust.","udesc":"Channel X+1 Lightning. Exhaust."},
            {"name":"White Noise","class":"Defect","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Add a random Power card into your hand. It costs 0 this turn. Exhaust.","udesc":""},
            {"name":"All for One","class":"Defect","type":"Attack","rarity":"Rare","cost":"2","desc":"Deal 10 (14) damage. Put all cost 0 cards from your discard pile into your hand.","udesc":""},
            {"name":"Amplify","class":"Defect","type":"Skill","rarity":"Rare","cost":"1","desc":"This turn, your next Power card is played twice.","udesc":"This turn, your next 2 Power cards are played twice."},
            {"name":"Biased Cognition","class":"Defect","type":"Power","rarity":"Rare","cost":"1","desc":"Gain 4 (5) Focus. At the start of your turn, lose 1 Focus.","udesc":""},
            {"name":"Buffer","class":"Defect","type":"Power","rarity":"Rare","cost":"2","desc":"Prevent the next time you would lose HP.","udesc":"Prevent the next 2 times you would lose HP."},
            {"name":"Core Surge","class":"Defect","type":"Attack","rarity":"Rare","cost":"1","desc":"Deal 11 (15) damage. Gain 1 Artifact. Exhaust.","udesc":""},
            {"name":"Creative AI","class":"Defect","type":"Power","rarity":"Rare","cost":"3 (2)","desc":"At the start of your turn, add a random Power card into your hand.","udesc":""},
            {"name":"Echo Form","class":"Defect","type":"Power","rarity":"Rare","cost":"3","desc":"Ethereal. The first card you play each turn is played twice.","udesc":"The first card you play each turn is played twice."},
            {"name":"Electrodynamics","class":"Defect","type":"Power","rarity":"Rare","cost":"2","desc":"Lightning now hits ALL enemies. Channel 2 (3) Lightning.","udesc":""},
            {"name":"Fission","class":"Defect","type":"Skill","rarity":"Rare","cost":"0","desc":"Remove all your Orbs. Gain [B] and draw 1 card for each Orb removed. Exhaust.","udesc":"Evoke all your Orbs. Gain [B] and draw 1 card for each Orb Evoked. Exhaust."},
            {"name":"Hyperbeam","class":"Defect","type":"Attack","rarity":"Rare","cost":"2","desc":"Deal 26 (34) damage to ALL enemies. Lose 3 Focus.","udesc":""},
            {"name":"Machine Learning","class":"Defect","type":"Power","rarity":"Rare","cost":"1","desc":"At the start of your turn, draw 1 additional card.","udesc":"Innate. At the start of your turn, draw 1 additional card."},
            {"name":"Meteor Strike","class":"Defect","type":"Attack","rarity":"Rare","cost":"5","desc":"Deal 24 (30) damage. Channel 3 Plasma.","udesc":""},
            {"name":"Multi-Cast","class":"Defect","type":"Skill","rarity":"Rare","cost":"X","desc":"Evoke your next Orb X times.","udesc":"Evoke your next Orb X+1 times."},
            {"name":"Rainbow","class":"Defect","type":"Skill","rarity":"Rare","cost":"2","desc":"Channel 1 Lightning. Channel 1 Frost. Channel 1 Dark. Exhaust.","udesc":"Channel 1 Lightning. Channel 1 Frost. Channel 1 Dark."},
            {"name":"Reboot","class":"Defect","type":"Skill","rarity":"Rare","cost":"0","desc":"Shuffle ALL your cards into your draw pile. Draw 4 (6) cards. Exhaust.","udesc":""},
            {"name":"Seek","class":"Defect","type":"Skill","rarity":"Rare","cost":"0","desc":"Put 1 card from your draw pile into your hand. Exhaust.","udesc":"Put 2 cards from your draw pile into your hand. Exhaust."},
            {"name":"Thunder Strike","class":"Defect","type":"Attack","rarity":"Rare","cost":"3","desc":"Deal 7 (9) damage to a random enemy for each Lightning Channeled this combat.","udesc":""},
            {"name":"Defend","class":"Watcher","type":"Skill","rarity":"Basic","cost":"1","desc":"Gain 5 (8) Block.","udesc":""},
            {"name":"Eruption","class":"Watcher","type":"Attack","rarity":"Basic","cost":"2 (1)","desc":"Deal 9 damage. Enter Wrath.","udesc":""},
            {"name":"Strike","class":"Watcher","type":"Attack","rarity":"Basic","cost":"1","desc":"Deal 6 (9) damage.","udesc":""},
            {"name":"Vigilance","class":"Watcher","type":"Skill","rarity":"Basic","cost":"2","desc":"Gain 8 (12) Block. Enter Calm.","udesc":""},
            {"name":"Bowling Bash","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (10) damage for each enemy in combat.","udesc":""},
            {"name":"Consecrate","class":"Watcher","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 5 (8) damage to ALL enemies.","udesc":""},
            {"name":"Crescendo","class":"Watcher","type":"Skill","rarity":"Common","cost":"1 (0)","desc":"Retain. Enter Wrath. Exhaust.","udesc":""},
            {"name":"Crush Joints","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 8 (10) damage. If the last card played this combat was a Skill, apply 1 (2) Vulnerable.","udesc":""},
            {"name":"Cut Through Fate","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (9) damage. Scry 2 (3). Draw 1 card.","udesc":""},
            {"name":"Empty Body","class":"Watcher","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 7 (10) Block. Exit your Stance.","udesc":""},
            {"name":"Empty Fist","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 9 (14) damage. Exit your Stance.","udesc":""},
            {"name":"Evaluate","class":"Watcher","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 6 (10) Block. Shuffle an Insight into your draw pile.","udesc":""},
            {"name":"Flurry of Blows","class":"Watcher","type":"Attack","rarity":"Common","cost":"0","desc":"Deal 4 (6) damage. Whenever you change Stances, return this from the discard pile to your hand.","udesc":""},
            {"name":"Flying Sleeves","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Retain. Deal 4 (6) damage twice.","udesc":""},
            {"name":"Follow-Up","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 7 (11) damage. If the last card played this combat was an Attack, gain [W].","udesc":""},
            {"name":"Halt","class":"Watcher","type":"Skill","rarity":"Common","cost":"0","desc":"Gain 3 (4) Block. If you are in Wrath, gain 9 (14) additional Block.","udesc":""},
            {"name":"Just Lucky","class":"Watcher","type":"Attack","rarity":"Common","cost":"0","desc":"Scry 1 (2). Gain 2 (3) Block. Deal 3 (4) damage.","udesc":""},
            {"name":"Pressure Points","class":"Watcher","type":"Skill","rarity":"Common","cost":"1","desc":"Apply 8 (11) Mark. ALL enemies lose HP equal to their Mark.","udesc":""},
            {"name":"Prostrate","class":"Watcher","type":"Skill","rarity":"Common","cost":"0","desc":"Gain 2 (3) Mantra. Gain 4 Block.","udesc":""},
            {"name":"Protect","class":"Watcher","type":"Skill","rarity":"Common","cost":"2","desc":"Retain. Gain 12 (16) Block.","udesc":""},
            {"name":"Sash Whip","class":"Watcher","type":"Attack","rarity":"Common","cost":"1","desc":"Deal 8 (10) damage. If the last card played this combat was an Attack, apply 1 (2) Weak.","udesc":""},
            {"name":"Third Eye","class":"Watcher","type":"Skill","rarity":"Common","cost":"1","desc":"Gain 7 (9) Block. Scry 3 (5).","udesc":""},
            {"name":"Tranquility","class":"Watcher","type":"Skill","rarity":"Common","cost":"1 (0)","desc":"Retain. Enter Calm. Exhaust.","udesc":""},
            {"name":"Battle Hymn","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the start of each turn, add a Smite into your hand.","udesc":"Innate. At the start of each turn, add a Smite into your hand."},
            {"name":"Carve Reality","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 6 (10) damage. Add a Smite into your hand.","udesc":""},
            {"name":"Collect","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"X","desc":"Put a Miracle+ into your hand at the start of your next X turns. Exhaust.","udesc":"Put a Miracle+ into your hand at the start of your next X+1 turns. Exhaust."},
            {"name":"Conclude","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 12 (16) damage to ALL enemies. End your turn.","udesc":""},
            {"name":"Deceive Reality","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain 4 (7) Block. Add a Safety into your hand.","udesc":""},
            {"name":"Empty Mind","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Draw 2 (3) cards. Exit your Stance.","udesc":""},
            {"name":"Fasting","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"2","desc":"Gain 3 (4) Strength. Gain 3 (4) Dexterity. Gain 1 less [W] at the start of each turn.","udesc":""},
            {"name":"Fear No Evil","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 8 (11) damage. If the enemy intends to Attack, enter Calm.","udesc":""},
            {"name":"Foreign Influence","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Choose 1 of 3 Attacks of any color to add into your hand. Exhaust.","udesc":"Choose 1 of 3 Attacks of any color to add into your hand. It costs 0 this turn. Exhaust."},
            {"name":"Foresight","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the start of your turn, Scry 3 (4).","udesc":""},
            {"name":"Indignation","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"If you are in Wrath, apply 3 (5) Vulnerable to ALL enemies, otherwise enter Wrath.","udesc":""},
            {"name":"Inner Peace","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"If you are in Calm, draw 3 (4) cards, otherwise enter Calm.","udesc":""},
            {"name":"Like Water","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"1","desc":"At the end of your turn, if you are in Calm, gain 5 (7) Block.","udesc":""},
            {"name":"Meditate","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Put a card from your discard pile into your hand and Retain it. Enter Calm. End your turn.","udesc":"Put 2 cards from your discard pile into your hand and Retain them. Enter Calm. End your turn."},
            {"name":"Mental Fortress","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you change Stances, gain 4 (6) Block.","udesc":""},
            {"name":"Nirvana","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"1","desc":"Whenever you Scry, gain 3 (4) Block.","udesc":""},
            {"name":"Perseverance","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Retain. Gain 5 (7) Block. When Retained, increase its Block by 2 (3) this combat.","udesc":""},
            {"name":"Pray","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain 3 (4) Mantra. Shuffle an Insight into your draw pile.","udesc":""},
            {"name":"Reach Heaven","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 10 (15) damage. Shuffle a Through Violence into your draw pile.","udesc":""},
            {"name":"Rushdown","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"1 (0)","desc":"Whenever you enter Wrath, draw 2 cards.","udesc":""},
            {"name":"Sanctity","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Gain 6 (9) Block. If the last card played this combat was a Skill, draw 2 cards.","udesc":""},
            {"name":"Sands of Time","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"4","desc":"Retain. Deal 20 (26) damage. When Retained, lower its cost by 1 this combat.","udesc":""},
            {"name":"Signature Move","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Can only be played if this is the only Attack in your hand. Deal 30 (40) damage.","udesc":""},
            {"name":"Simmering Fury","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"At the start of your next turn, enter Wrath and draw 2 (3) cards.","udesc":""},
            {"name":"Study","class":"Watcher","type":"Power","rarity":"Uncommon","cost":"2 (1)","desc":"At the end of your turn, shuffle an Insight into your draw pile.","udesc":""},
            {"name":"Swivel","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Gain 8 (11) Block. The next Attack you play costs 0.","udesc":""},
            {"name":"Talk to the Hand","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 5 (7) damage. Whenever you attack this enemy, gain 2 (3) Block. Exhaust.","udesc":""},
            {"name":"Tantrum","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"1","desc":"Deal 3 damage 3 (4) times. Enter Wrath. Shuffle this card into your draw pile.","udesc":""},
            {"name":"Wallop","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 9 (12) damage. Gain Block equal to unblocked damage dealt.","udesc":""},
            {"name":"Wave of the Hand","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Whenever you gain Block this turn, apply 1 (2) Weak to ALL enemies.","udesc":""},
            {"name":"Weave","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Deal 4 (6) damage. Whenever you Scry, return this from the discard pile to your Hand.","udesc":""},
            {"name":"Wheel Kick","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Deal 15 (20) damage. Draw 2 cards.","udesc":""},
            {"name":"Windmill Strike","class":"Watcher","type":"Attack","rarity":"Uncommon","cost":"2","desc":"Retain. Deal 7 (10) damage. When Retained, increase its damage by 4 (5) this combat.","udesc":""},
            {"name":"Worship","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"2","desc":"Gain 5 Mantra.","udesc":"Retain. Gain 5 Mantra."},
            {"name":"Wreath of Flame","class":"Watcher","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Your next Attack deals 5 (8) additional damage.","udesc":""},
            {"name":"Alpha","class":"Watcher","type":"Skill","rarity":"Rare","cost":"1","desc":"Shuffle a Beta into your draw pile. Exhaust.","udesc":"Innate. Shuffle a Beta into your draw pile. Exhaust."},
            {"name":"Blasphemy","class":"Watcher","type":"Skill","rarity":"Rare","cost":"1","desc":"Enter Divinity. Die next turn. Exhaust.","udesc":"Retain. Enter Divinity. Die next turn. Exhaust."},
            {"name":"Brilliance","class":"Watcher","type":"Attack","rarity":"Rare","cost":"1","desc":"Deal 12 (16) damage. Deals additional damage equal to Mantra gained this combat.","udesc":""},
            {"name":"Conjure Blade","class":"Watcher","type":"Skill","rarity":"Rare","cost":"X","desc":"Shuffle an Expunger into your draw pile. Exhaust.","udesc":"Shuffle an Expunger with X+1 into your draw pile. Exhaust."},
            {"name":"Deus Ex Machina","class":"Watcher","type":"Skill","rarity":"Rare","cost":"-","desc":"Unplayable. When you draw this card, add 2 (3) Miracles to your hand and Exhaust.","udesc":""},
            {"name":"Deva Form","class":"Watcher","type":"Power","rarity":"Rare","cost":"3","desc":"Ethereal. At the start of your turn, gain [W] and increase this gain by 1.","udesc":"At the start of your turn, gain [W] and increase this gain by 1."},
            {"name":"Devotion","class":"Watcher","type":"Power","rarity":"Rare","cost":"1","desc":"At the start of your turn, gain 2 (3) Mantra.","udesc":""},
            {"name":"Establishment","class":"Watcher","type":"Power","rarity":"Rare","cost":"1","desc":"Whenever a card is Retained, reduce its cost by 1 this combat.","udesc":"Innate. Whenever a card is Retained, reduce its cost by 1 this combat."},
            {"name":"Judgment","class":"Watcher","type":"Skill","rarity":"Rare","cost":"1","desc":"If the enemy has 30 (40) or less HP, set their HP to 0.","udesc":""},
            {"name":"Lesson Learned","class":"Watcher","type":"Attack","rarity":"Rare","cost":"2","desc":"Deal 10 (13) damage. If Fatal, Upgrade a random card in your deck. Exhaust.","udesc":""},
            {"name":"Master Reality","class":"Watcher","type":"Power","rarity":"Rare","cost":"1 (0)","desc":"Whenever a card is created during combat, Upgrade it.","udesc":""},
            {"name":"Omniscience","class":"Watcher","type":"Skill","rarity":"Rare","cost":"4 (3)","desc":"Choose a card in your draw pile. Play the chosen card twice and exhaust it. Exhaust.","udesc":""},
            {"name":"Ragnarok","class":"Watcher","type":"Attack","rarity":"Rare","cost":"3","desc":"Deal 5 (6) damage to a random enemy 5 (6) times.","udesc":""},
            {"name":"Scrawl","class":"Watcher","type":"Skill","rarity":"Rare","cost":"1 (0)","desc":"Draw cards until your hand is full. Exhaust.","udesc":""},
            {"name":"Spirit Shield","class":"Watcher","type":"Skill","rarity":"Rare","cost":"2","desc":"Gain 3 (4) Block for each card in your hand.","udesc":""},
            {"name":"Vault","class":"Watcher","type":"Skill","rarity":"Rare","cost":"3 (2)","desc":"Take an extra turn after this one. End your turn. Exhaust.","udesc":""},
            {"name":"Wish","class":"Watcher","type":"Skill","rarity":"Rare","cost":"3","desc":"Choose one: Gain 6 (8) Plated Armor, 3 (4) Strength, or 25 (30) Gold. Exhaust.","udesc":""},
            {"name":"Bandage Up","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Heal 4 (6) HP. Exhaust.","udesc":""},
            {"name":"Blind","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Apply 2 Weak.","udesc":"Apply 2 Weak to ALL enemies."},
            {"name":"Dark Shackles","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Enemy loses 9 (15) Strength this turn. Exhaust.","udesc":""},
            {"name":"Deep Breath","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Shuffle your discard pile into your draw pile. Draw 1 card.","udesc":"Shuffle your discard pile into your draw pile. Draw 2 cards."},
            {"name":"Discovery","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"1","desc":"Choose 1 of 3 random cards to add into your hand. It costs 0 this turn. Exhaust.","udesc":"Choose 1 of 3 random cards to add into your hand. It costs 0 this turn."},
            {"name":"Dramatic Entrance","class":"Colorless","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Innate. Deal 8 (12) damage to ALL enemies. Exhaust.","udesc":""},
            {"name":"Enlightenment","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Reduce the cost of all cards in your hand to 1 this turn.","udesc":"Reduce the cost of all cards in your hand to 1 this combat."},
            {"name":"Finesse","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Gain 2 (4) Block. Draw 1 card.","udesc":""},
            {"name":"Flash of Steel","class":"Colorless","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Deal 3 (6) damage. Draw 1 card.","udesc":""},
            {"name":"Forethought","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Put a card from your hand to the bottom of your draw pile. It costs 0 until played.","udesc":"Put any number of cards from your hand to the bottom of your draw pile. They cost 0 until played."},
            {"name":"Good Instincts","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Gain 6 (9) Block.","udesc":""},
            {"name":"Impatience","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"If you have no Attacks in your hand, draw 2 (3) cards.","udesc":""},
            {"name":"Jack of All Trades","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Add 1 random Colorless card into your hand. Exhaust.","udesc":"Add 2 random Colorless cards into your hand. Exhaust."},
            {"name":"Madness","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"1 (0)","desc":"Reduce the cost of a random card in your hand to 0 this combat. Exhaust.","udesc":""},
            {"name":"Mind Blast","class":"Colorless","type":"Attack","rarity":"Uncommon","cost":"2 (1)","desc":"Innate. Deal damage equal to the number of cards in your draw pile.","udesc":""},
            {"name":"Panacea","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Gain 1 (2) Artifact. Exhaust.","udesc":""},
            {"name":"Panic Button","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Gain 30 (40) Block. You cannot gain Block from cards for 2 turns. Exhaust.","udesc":""},
            {"name":"Purity","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Exhaust up to 3 (5) cards in your hand. Exhaust.","udesc":""},
            {"name":"Swift Strike","class":"Colorless","type":"Attack","rarity":"Uncommon","cost":"0","desc":"Deal 7 (10) damage.","udesc":""},
            {"name":"Trip","class":"Colorless","type":"Skill","rarity":"Uncommon","cost":"0","desc":"Apply 2 Vulnerable.","udesc":"Apply 2 Vulnerable to ALL enemies."},
            {"name":"Apotheosis","class":"Colorless","type":"Skill","rarity":"Rare","cost":"2 (1)","desc":"Upgrade ALL your cards for the rest of combat. Exhaust.","udesc":""},
            {"name":"Chrysalis","class":"Colorless","type":"Skill","rarity":"Rare","cost":"2","desc":"Shuffle 3 (5) random Skills into your draw pile. They cost 0 this combat. Exhaust.","udesc":""},
            {"name":"Hand of Greed","class":"Colorless","type":"Attack","rarity":"Rare","cost":"2","desc":"Deal 20 (25) damage. If Fatal, gain 20 (25) Gold.","udesc":""},
            {"name":"Magnetism","class":"Colorless","type":"Power","rarity":"Rare","cost":"2 (1)","desc":"At the start of your turn, add a random Colorless card into your hand.","udesc":""},
            {"name":"Master of Strategy","class":"Colorless","type":"Skill","rarity":"Rare","cost":"0","desc":"Draw 3 (4) cards. Exhaust.","udesc":""},
            {"name":"Mayhem","class":"Colorless","type":"Power","rarity":"Rare","cost":"2 (1)","desc":"At the start of your turn, play the top card of your draw pile.","udesc":""},
            {"name":"Metamorphosis","class":"Colorless","type":"Skill","rarity":"Rare","cost":"2","desc":"Shuffle 3 (5) random Attacks into your draw pile. They cost 0 this combat. Exhaust.","udesc":""},
            {"name":"Panache","class":"Colorless","type":"Power","rarity":"Rare","cost":"0","desc":"Every time you play 5 cards in a single turn, deal 10 (14) damage to ALL enemies.","udesc":""},
            {"name":"Sadistic Nature","class":"Colorless","type":"Power","rarity":"Rare","cost":"0","desc":"Whenever you apply a debuff to an enemy, they take 5 (7) damage.","udesc":""},
            {"name":"Secret Technique","class":"Colorless","type":"Skill","rarity":"Rare","cost":"0","desc":"Put a Skill from your draw pile into your hand. Exhaust.","udesc":"Put a Skill from your draw pile into your hand."},
            {"name":"Secret Weapon","class":"Colorless","type":"Skill","rarity":"Rare","cost":"0","desc":"Put an Attack from your draw pile into your hand. Exhaust.","udesc":"Put an Attack from your draw pile into your hand."},
            {"name":"The Bomb","class":"Colorless","type":"Skill","rarity":"Rare","cost":"2","desc":"At the end of 3 turns, deal 40 (50) damage to ALL enemies.","udesc":""},
            {"name":"Thinking Ahead","class":"Colorless","type":"Skill","rarity":"Rare","cost":"0","desc":"Draw 2 cards. Put a card from your hand on top of your draw pile. Exhaust.","udesc":"Draw 2 cards. Put a card from your hand on top of your draw pile."},
            {"name":"Transmutation","class":"Colorless","type":"Skill","rarity":"Rare","cost":"X","desc":"Add X random Colorless cards into your hand. They cost 0 this turn. Exhaust.","udesc":"Add X random Upgraded Colorless cards into your hand. They cost 0 this turn. Exhaust."},
            {"name":"Violence","class":"Colorless","type":"Skill","rarity":"Rare","cost":"0","desc":"Put 3 (4) random Attacks from your draw pile into your hand. Exhaust.","udesc":""},
            {"name":"Apparition","class":"Special","type":"Skill","rarity":"Special","cost":"1","desc":"Ethereal. Gain 1 Intangible. Exhaust.","udesc":"Gain 1 Intangible. Exhaust."},
            {"name":"Become Almighty","class":"Special","type":"Power","rarity":"Special","cost":"-","desc":"Gain 3 (4) Strength.","udesc":""},
            {"name":"Beta","class":"Special","type":"Skill","rarity":"Special","cost":"2 (1)","desc":"Shuffle an Omega into your draw pile. Exhaust.","udesc":""},
            {"name":"Bite","class":"Special","type":"Attack","rarity":"Special","cost":"1","desc":"Deal 7 (8) damage. Heal 2 (3) HP.","udesc":""},
            {"name":"Expunger","class":"Special","type":"Attack","rarity":"Special","cost":"1","desc":"Deal 9 (15) damage X times.","udesc":""},
            {"name":"Fame and Fortune","class":"Special","type":"Skill","rarity":"Special","cost":"-","desc":"Gain 25 (30) Gold.","udesc":""},
            {"name":"Insight","class":"Special","type":"Skill","rarity":"Special","cost":"0","desc":"Retain. Draw 2 (3) cards. Exhaust.","udesc":""},
            {"name":"J.A.X.","class":"Special","type":"Skill","rarity":"Special","cost":"0","desc":"Lose 3 HP. Gain 2 (3) Strength.","udesc":""},
            {"name":"Live Forever","class":"Special","type":"Power","rarity":"Special","cost":"-","desc":"Gain 6 (8) Plated Armor.","udesc":""},
            {"name":"Miracle","class":"Special","type":"Skill","rarity":"Special","cost":"0","desc":"Retain. Gain [W]. Exhaust.","udesc":"Retain. Gain [W] [W]. Exhaust."},
            {"name":"Omega","class":"Special","type":"Power","rarity":"Special","cost":"3","desc":"At the end of your turn, deal 50 (60) damage to ALL enemies.","udesc":""},
            {"name":"Ritual Dagger","class":"Special","type":"Attack","rarity":"Special","cost":"1","desc":"Deal 15 damage. If Fatal, permanently increase this card's damage by 3 (5). Exhaust.","udesc":""},
            {"name":"Safety","class":"Special","type":"Skill","rarity":"Special","cost":"1","desc":"Retain. Gain 12 (16) Block. Exhaust.","udesc":""},
            {"name":"Shiv","class":"Special","type":"Attack","rarity":"Special","cost":"0","desc":"Deal 4 (6) damage. Exhaust.","udesc":""},
            {"name":"Smite","class":"Special","type":"Attack","rarity":"Special","cost":"1","desc":"Retain. Deal 12 (16) damage. Exhaust.","udesc":""},
            {"name":"Through Violence","class":"Special","type":"Attack","rarity":"Special","cost":"0","desc":"Retain. Deal 20 (30) damage. Exhaust.","udesc":""},
            {"name":"Clumsy","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. Ethereal.","udesc":""},
            {"name":"Decay","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. At the end of your turn, take 2 damage.","udesc":""},
            {"name":"Doubt","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. At the end of your turn, gain 1 Weak.","udesc":""},
            {"name":"Injury","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable.","udesc":""},
            {"name":"Normality","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. While in hand, you cannot play more than 3 cards this turn.","udesc":""},
            {"name":"Pain","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. While in hand, lose 1 HP whenever you play another card.","udesc":""},
            {"name":"Parasite","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. If transformed or removed from your deck, lose 3 Max HP.","udesc":""},
            {"name":"Regret","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. At the end of your turn, lose HP equal to the number of cards in your hand.","udesc":""},
            {"name":"Shame","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. At the end of your turn, gain 1 Frail.","udesc":""},
            {"name":"Writhe","class":"Bad","type":"Curse","rarity":"Curse","cost":"-","desc":"Unplayable. Innate.","udesc":""},
            {"name":"Ascender's Bane","class":"Bad","type":"Curse","rarity":"Special","cost":"-","desc":"Unplayable. Ethereal. Cannot be removed from your deck.","udesc":""},
            {"name":"Curse of the Bell","class":"Bad","type":"Curse","rarity":"Special","cost":"-","desc":"Unplayable. Cannot be removed from your deck.","udesc":""},
            {"name":"Necronomicurse","class":"Bad","type":"Curse","rarity":"Special","cost":"-","desc":"Unplayable. There is no escape from this Curse.","udesc":""},
            {"name":"Pride","class":"Bad","type":"Curse","rarity":"Special","cost":"1","desc":"Innate. At the end of your turn, put a copy of this card on top of your draw pile. Exhaust.","udesc":""},
            {"name":"Burn","class":"Bad","type":"Status","rarity":"Common","cost":"-","desc":"Unplayable. At the end of your turn, take 2 damage.","udesc":""},
            {"name":"Dazed","class":"Bad","type":"Status","rarity":"Common","cost":"-","desc":"Unplayable. Ethereal.","udesc":""},
            {"name":"Slimed","class":"Bad","type":"Status","rarity":"Common","cost":"1","desc":"Exhaust.","udesc":""},
            {"name":"Void","class":"Bad","type":"Status","rarity":"Common","cost":"-","desc":"Unplayable. Ethereal. Whenever this card is drawn, lose 1 Energy.","udesc":""},
            {"name":"Wound","class":"Bad","type":"Status","rarity":"Common","cost":"-","desc":"Unplayable.","udesc":""}
        ]
    };
    setDataToTable(jsonData);
}

function setDataToTable(jsonData){
	$('#cards').DataTable( {
        pagination: "bootstrap",
            filter: true,
            data: jsonData.data,
            destroy: true,
            lengthMenu: [10,25,50,75,100],
            pageLength: 50,
            "columns":
            [  
                {"data": "name"},
                {"data": "class"},
                {"data": "type"},
                {"data": "rarity"},
                {"data": "cost"},
                {"data": "desc"},
                {"data": "udesc"}
            ]
        } 
    );
}